### ISSUE TITLE
有界面可以预览一下吗


### ISSUE THREAD

**Issue by leeima** [witchx/libseat#1]

**Comment by witchx** [comment]
![微信图片_20230824123614](https://github.com/witchx/libseat/assets/59158259/2c749d0b-cd2a-4a5a-a957-35499a391a9c)
![微信图片_20230824123615](https://github.com/witchx/libseat/assets/59158259/66002d98-994b-4976-88fb-4e56bef64b15)
![微信图片_20230824123616](https://github.com/witchx/libseat/assets/59158259/dd7519fe-7cd8-46d8-8c9d-b56ad66c4843)
![微信图片_20230824123617](https://github.com/witchx/libseat/assets/59158259/a0d2641a-ff6a-405c-a553-e48cdb8d33a9)
![微信图片_20230824123618](https://github.com/witchx/libseat/assets/59158259/8ffab97e-3eab-4f1b-95dd-bbce68065e05)

**Comment by witchx** [comment]
![微信图片_20230824123614](https://github.com/witchx/libseat/assets/59158259/2b0a35d6-6535-444f-b03c-60ced298cb0f)
![微信图片_20230824123615](https://github.com/witchx/libseat/assets/59158259/1c8e3db2-e7a1-4ae3-b728-749ee860f8fc)
![微信图片_20230824123618](https://github.com/witchx/libseat/assets/59158259/f0ac805a-b031-4796-ae84-ae4360973b46)
![微信图片_20230824123616](https://github.com/witchx/libseat/assets/59158259/782e819c-2683-4d80-939f-17dccf57e262)
